/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-09-18 02:32:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.Shain;

public final class shain_005fitirann_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("model.Shain");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ja\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>社員一覧</title>\n");
      out.write("  <style>\n");
      out.write("    body { font-family: \"ヒラギノ角ゴ ProN\", Meiryo, sans-serif; background-color: #f9f9f9; padding:30px; }\n");
      out.write("    h1 { color:#333; margin-bottom:20px; }\n");
      out.write("    table { border-collapse: collapse; width:100%; max-width:800px; background:#fff; border-radius:8px; box-shadow:0 2px 6px rgba(0,0,0,0.1); }\n");
      out.write("    th, td { border:1px solid #ccc; padding:10px 12px; text-align:left; font-size:14px; }\n");
      out.write("    th { background-color:#4caf50; color:white; }\n");
      out.write("    tr:nth-child(even){ background-color:#f2f2f2; }\n");
      out.write("    a { color:#4caf50; text-decoration:none; font-weight:bold; }\n");
      out.write("    a:hover { text-decoration:underline; }\n");
      out.write("    .container { max-width:820px; margin:0 auto; }\n");
      out.write("    .btn-back { display:inline-block; margin-top:20px; background-color:#4caf50; color:white; padding:8px 16px; border-radius:4px; text-decoration:none; font-weight:bold; }\n");
      out.write("    .btn-back:hover { background-color:#45a049; }\n");
      out.write("\n");
      out.write("    /* 検索フォーム用テーブル風デザイン */\n");
      out.write("    .search-form { width:100%; max-width:800px; margin-bottom:20px; border-collapse: collapse; background:#fff; border-radius:8px; box-shadow:0 2px 6px rgba(0,0,0,0.1); }\n");
      out.write("    .search-form td { padding:8px 12px; font-size:14px; }\n");
      out.write("    .search-form input, .search-form select { padding:4px 6px; border:1px solid #ccc; border-radius:4px; }\n");
      out.write("    .search-form button { background-color:#4caf50; color:white; padding:6px 12px; border:none; border-radius:4px; cursor:pointer; font-weight:bold; }\n");
      out.write("    .search-form button:hover { background-color:#45a049; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <h1>社員一覧</h1>\n");
      out.write("\n");
      out.write("  <!-- 検索フォーム -->\n");
      out.write("  <form class=\"search-form\" action=\"shain_itirann\" method=\"get\">\n");
      out.write("    <table>\n");
      out.write("      <tr>\n");
      out.write("        <td>氏名</td>\n");
      out.write("        <td><input type=\"text\" name=\"name\" value=\"");
      out.print( request.getParameter("name") != null ? request.getParameter("name") : "" );
      out.write("\"></td>\n");
      out.write("        <td>性別</td>\n");
      out.write("        <td>\n");
      out.write("          <select name=\"gender\">\n");
      out.write("            <option value=\"\">全て</option>\n");
      out.write("            <option value=\"M\" ");
      out.print( "M".equals(request.getParameter("gender")) ? "selected" : "" );
      out.write(">男性</option>\n");
      out.write("            <option value=\"F\" ");
      out.print( "F".equals(request.getParameter("gender")) ? "selected" : "" );
      out.write(">女性</option>\n");
      out.write("          </select>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td>備考</td>\n");
      out.write("        <td><input type=\"text\" name=\"note\" value=\"");
      out.print( request.getParameter("note") != null ? request.getParameter("note") : "" );
      out.write("\"></td>\n");
      out.write("        <td>ソート</td>\n");
      out.write("        <td>\n");
      out.write("          <select name=\"sort\">\n");
      out.write("            <option value=\"id\" ");
      out.print( "id".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">社員ID</option>\n");
      out.write("            <option value=\"name\" ");
      out.print( "name".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">氏名</option>\n");
      out.write("            <option value=\"gender\" ");
      out.print( "gender".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">性別</option>\n");
      out.write("            <option value=\"note\" ");
      out.print( "note".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">備考</option>\n");
      out.write("          </select>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td>順序</td>\n");
      out.write("        <td>\n");
      out.write("          <select name=\"order\">\n");
      out.write("            <option value=\"asc\" ");
      out.print( "asc".equals(request.getParameter("order")) ? "selected" : "" );
      out.write(">昇順</option>\n");
      out.write("            <option value=\"desc\" ");
      out.print( "desc".equals(request.getParameter("order")) ? "selected" : "" );
      out.write(">降順</option>\n");
      out.write("          </select>\n");
      out.write("        </td>\n");
      out.write("        <td colspan=\"2\"><button type=\"submit\">検索</button></td>\n");
      out.write("      </tr>\n");
      out.write("    </table>\n");
      out.write("  </form>\n");
      out.write("\n");
      out.write("  ");
 
    List<Shain> shainList = (List<Shain>) request.getAttribute("shainList");
    if (shainList == null || shainList.isEmpty()) {
  
      out.write("\n");
      out.write("      <p>条件に一致する社員はいません。</p>\n");
      out.write("  ");
 } else { 
      out.write("\n");
      out.write("    <table>\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          <th>社員ID</th>\n");
      out.write("          <th>氏名</th>\n");
      out.write("          <th>性別</th>\n");
      out.write("          <th>備考</th>\n");
      out.write("          <th>操作</th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("      ");
 for (Shain s : shainList) { 
      out.write("\n");
      out.write("        <tr>\n");
      out.write("          <td>");
      out.print( s.getId() );
      out.write("</td>\n");
      out.write("          <td>");
      out.print( s.getName() );
      out.write("</td>\n");
      out.write("          <td>");
      out.print( "M".equals(s.getGender()) ? "男性" : "女性" );
      out.write("</td>\n");
      out.write("          <td>");
      out.print( s.getNote() != null ? s.getNote() : "" );
      out.write("</td>\n");
      out.write("          <td>\n");
      out.write("            <a href=\"shain_hensyuu?id=");
      out.print( s.getId() );
      out.write("\">更新</a> |\n");
      out.write("            <form action=\"shain_sakujyo\" method=\"post\" style=\"display:inline;\">\n");
      out.write("              <input type=\"hidden\" name=\"id\" value=\"");
      out.print( s.getId() );
      out.write("\">\n");
      out.write("              <button type=\"submit\" onclick=\"return confirm('本当に削除しますか？');\" style=\"background:none; border:none; color:#4caf50; font-weight:bold; cursor:pointer;\">削除</button>\n");
      out.write("            </form>\n");
      out.write("          </td>\n");
      out.write("        </tr>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <a href=\"shain_touroku\" class=\"btn-back\">社員登録へ戻る</a>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
