/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-09-18 02:22:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class shain_005fhensyuu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ja\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<title>社員編集フォーム</title>\n");
      out.write("<style>\n");
      out.write("  html, body {\n");
      out.write("    height: 100%;\n");
      out.write("    margin: 0;\n");
      out.write("    font-family: \"ヒラギノ角ゴ ProN\", \"Hiragino Kaku Gothic ProN\", Meiryo, sans-serif;\n");
      out.write("    background-color: #f9f9f9;\n");
      out.write("  }\n");
      out.write("  body {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("  }\n");
      out.write("  .form-container {\n");
      out.write("    background: #fff;\n");
      out.write("    padding: 30px 40px;\n");
      out.write("    border-radius: 8px;\n");
      out.write("    box-shadow: 0 2px 6px rgba(0,0,0,0.1);\n");
      out.write("    width: 450px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  h1 {\n");
      out.write("    color: #333;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    text-align: center;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  label {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 70px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    vertical-align: top;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  input[type=\"text\"],\n");
      out.write("  textarea {\n");
      out.write("    width: calc(100% - 80px);\n");
      out.write("    padding: 6px 8px;\n");
      out.write("    border: 1px solid #ccc;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    font-size: 14px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  textarea {\n");
      out.write("    resize: vertical;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  input[type=\"radio\"] {\n");
      out.write("    margin-left: 10px;\n");
      out.write("    margin-right: 4px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .btn-group {\n");
      out.write("    margin-top: 15px;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .btn-left {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 8px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  input[type=\"submit\"],\n");
      out.write("  input[type=\"reset\"],\n");
      out.write("  .btn-list {\n");
      out.write("    background-color: #4caf50;\n");
      out.write("    color: white;\n");
      out.write("    border: none;\n");
      out.write("    padding: 8px 16px;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    font-size: 15px;\n");
      out.write("    transition: background-color 0.3s ease;\n");
      out.write("    text-decoration: none;\n");
      out.write("    display: inline-block;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  input[type=\"reset\"] {\n");
      out.write("    background-color: #f44336;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  input[type=\"submit\"]:hover {\n");
      out.write("    background-color: #45a049;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  input[type=\"reset\"]:hover {\n");
      out.write("    background-color: #d32f2f;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .btn-list:hover {\n");
      out.write("    background-color: #388e3c;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"form-container\">\n");
      out.write("    <h1>社員編集フォーム</h1>\n");
      out.write("\n");
      out.write("    ");
 
        Object idObj = request.getAttribute("ユーザーID");
        String id = idObj != null ? String.valueOf(idObj) : "";
    
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"shain_hensyuu\" method=\"post\">\n");
      out.write("      <input type=\"hidden\" name=\"ユーザーID\" value=\"");
      out.print( id );
      out.write("\">\n");
      out.write("\n");
      out.write("      <label for=\"name\">氏名：</label>\n");
      out.write("      <input type=\"text\" id=\"name\" name=\"氏名\" required \n");
      out.write("             value=\"");
      out.print( request.getAttribute("氏名") != null ? String.valueOf(request.getAttribute("氏名")) : "" );
      out.write("\">\n");
      out.write("      <br><br>\n");
      out.write("\n");
      out.write("      <label>性別：</label>\n");
      out.write("      <input type=\"radio\" id=\"male\" name=\"性別\" value=\"M\"\n");
      out.write("        ");
      out.print( "M".equals(String.valueOf(request.getAttribute("性別"))) ? "checked" : "" );
      out.write(">\n");
      out.write("      <label for=\"male\">男性</label>\n");
      out.write("\n");
      out.write("      <input type=\"radio\" id=\"female\" name=\"性別\" value=\"F\"\n");
      out.write("        ");
      out.print( "F".equals(String.valueOf(request.getAttribute("性別"))) ? "checked" : "" );
      out.write(">\n");
      out.write("      <label for=\"female\">女性</label>\n");
      out.write("      <br><br>\n");
      out.write("\n");
      out.write("      <label for=\"bikou\">備考：</label><br>\n");
      out.write("      <textarea id=\"bikou\" name=\"備考\" rows=\"5\" cols=\"40\">\n");
      out.print( request.getAttribute("備考") != null ? String.valueOf(request.getAttribute("備考")) : "" );
      out.write("</textarea>\n");
      out.write("      <br><br>\n");
      out.write("\n");
      out.write("      ");
 String error = (String) request.getAttribute("errorMessage"); 
      out.write("\n");
      out.write("      ");
 if (error != null) { 
      out.write("\n");
      out.write("        <div style=\"color:red; font-size: 14px;\">");
      out.print( error );
      out.write("</div><br>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"btn-group\">\n");
      out.write("        <div class=\"btn-left\">\n");
      out.write("          <input type=\"submit\" value=\"更新\">\n");
      out.write("          <input type=\"reset\" value=\"リセット\">\n");
      out.write("        </div>\n");
      out.write("        <a href=\"shain_itirann\" class=\"btn-list\">社員一覧へ</a>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
