/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-09-12 03:39:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import model.Shain;

public final class shain_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.Shain");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>社員一覧</title>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("  font-family: sans-serif;\n");
      out.write("  max-width: 800px;\n");
      out.write("  margin: 40px auto;\n");
      out.write("  padding: 20px;\n");
      out.write("  background: #fafafa;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("  text-align: center;\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("  width: 100%;\n");
      out.write("  border-collapse: collapse;\n");
      out.write("}\n");
      out.write("\n");
      out.write("th, td {\n");
      out.write("  border: 1px solid #ddd;\n");
      out.write("  padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("th {\n");
      out.write("  background: #f2f2f2;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bikou-cell {\n");
      out.write("  max-width: 200px;\n");
      out.write("  white-space: nowrap;\n");
      out.write("  overflow: hidden;\n");
      out.write("  text-overflow: ellipsis;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".no-data {\n");
      out.write("  text-align: center;\n");
      out.write("  color: #777;\n");
      out.write("  padding: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button {\n");
      out.write("  padding: 6px 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a.button {\n");
      out.write("  display: inline-block;\n");
      out.write("  margin-bottom: 15px;\n");
      out.write("  padding: 6px 12px;\n");
      out.write("  background: #4285f4;\n");
      out.write("  color: white;\n");
      out.write("  text-decoration: none;\n");
      out.write("  border-radius: 4px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h2>社員一覧</h2>\n");
      out.write("<a href=\"maintenance?action=add\" class=\"button\">新規登録</a>\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("  <tr>\n");
      out.write("    <th>ユーザID</th>\n");
      out.write("    <th>氏名</th>\n");
      out.write("    <th>性別</th>\n");
      out.write("    <th>備考</th>\n");
      out.write("    <th>操作</th>\n");
      out.write("  </tr>\n");
      out.write("\n");
      out.write("  ");

    List<Shain> list = (List<Shain>) request.getAttribute("shainList");
    if (list != null && !list.isEmpty()) {
        for (Shain s : list) {
  
      out.write("\n");
      out.write("  <tr>\n");
      out.write("    <td>");
      out.print( s.getId() );
      out.write("</td>\n");
      out.write("    <td>");
      out.print( s.getName() );
      out.write("</td>\n");
      out.write("    <td>");
      out.print( s.getGenderLabel() );
      out.write("</td>\n");
      out.write("    <td class=\"bikou-cell\">");
      out.print( s.getNote() != null ? s.getNote() : "" );
      out.write("</td>\n");
      out.write("    <td>\n");
      out.write("      <form action=\"maintenance\" method=\"get\">\n");
      out.write("        <input type=\"hidden\" name=\"action\" value=\"edit\">\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( s.getId() );
      out.write("\">\n");
      out.write("        <button type=\"submit\">編集</button>\n");
      out.write("      </form>\n");
      out.write("      <form action=\"maintenance\" method=\"get\">\n");
      out.write("        <input type=\"hidden\" name=\"action\" value=\"delete\">\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( s.getId() );
      out.write("\">\n");
      out.write("        <button type=\"submit\">削除</button>\n");
      out.write("      </form>\n");
      out.write("    </td>\n");
      out.write("  </tr>\n");
      out.write("  ");
 } } else { 
      out.write("\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"5\" class=\"no-data\">データがありません</td>\n");
      out.write("  </tr>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
