/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-09-12 04:22:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.Shain;

public final class shain_005fitirann_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("model.Shain");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ja\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>社員一覧</title>\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      font-family: \"ヒラギノ角ゴ ProN\", \"Hiragino Kaku Gothic ProN\", Meiryo, sans-serif;\n");
      out.write("      background-color: #f9f9f9;\n");
      out.write("      padding: 30px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    h1 {\n");
      out.write("      color: #333;\n");
      out.write("      margin-bottom: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    table {\n");
      out.write("      border-collapse: collapse;\n");
      out.write("      width: 100%;\n");
      out.write("      max-width: 800px;\n");
      out.write("      background: #fff;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      box-shadow: 0 2px 6px rgba(0,0,0,0.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    th, td {\n");
      out.write("      border: 1px solid #ccc;\n");
      out.write("      padding: 10px 12px;\n");
      out.write("      text-align: left;\n");
      out.write("      font-size: 14px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    th {\n");
      out.write("      background-color: #4caf50;\n");
      out.write("      color: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    tr:nth-child(even) {\n");
      out.write("      background-color: #f2f2f2;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    a {\n");
      out.write("      color: #4caf50;\n");
      out.write("      text-decoration: none;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    a:hover {\n");
      out.write("      text-decoration: underline;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .container {\n");
      out.write("      max-width: 820px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-back {\n");
      out.write("      display: inline-block;\n");
      out.write("      margin-top: 20px;\n");
      out.write("      background-color: #4caf50;\n");
      out.write("      color: white;\n");
      out.write("      padding: 8px 16px;\n");
      out.write("      border-radius: 4px;\n");
      out.write("      text-decoration: none;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("    .btn-back:hover {\n");
      out.write("      background-color: #45a049;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h1>社員一覧</h1>\n");
      out.write("    ");

	    String flashMessage = (String) session.getAttribute("flashMessage");
	    String flashType = (String) session.getAttribute("flashType");
	    if (flashMessage != null) {
	        String colorClass = "flash-success";
	        if ("error".equals(flashType)) {
	            colorClass = "flash-error";
	        }
	
      out.write("\n");
      out.write("	<div id=\"flash-message\" class=\"");
      out.print( colorClass );
      out.write('"');
      out.write('>');
      out.print( flashMessage );
      out.write("</div>\n");
      out.write("	<script>\n");
      out.write("	  setTimeout(() => {\n");
      out.write("	    const flash = document.getElementById(\"flash-message\");\n");
      out.write("	    flash.style.transition = \"opacity 1s ease\";\n");
      out.write("	    flash.style.opacity = \"0\";\n");
      out.write("	    setTimeout(() => flash.remove(), 1000);\n");
      out.write("	  }, 2000);\n");
      out.write("	</script>\n");
      out.write("	");

	        session.removeAttribute("flashMessage");
	        session.removeAttribute("flashType");
	    }
	
      out.write("\n");
      out.write("	\n");
      out.write("	<style>\n");
      out.write("	  #flash-message {\n");
      out.write("	    position: fixed;\n");
      out.write("	    top: 10px;\n");
      out.write("	    left: 50%;\n");
      out.write("	    transform: translateX(-50%);\n");
      out.write("	    color: white;\n");
      out.write("	    padding: 12px 24px;\n");
      out.write("	    border-radius: 6px;\n");
      out.write("	    font-weight: bold;\n");
      out.write("	    box-shadow: 0 2px 8px rgba(0,0,0,0.2);\n");
      out.write("	    z-index: 9999;\n");
      out.write("	    opacity: 1;\n");
      out.write("	  }\n");
      out.write("	  .flash-success {\n");
      out.write("	    background-color: #4caf50; /* 緑 */\n");
      out.write("	  }\n");
      out.write("	  .flash-error {\n");
      out.write("	    background-color: #f44336; /* 赤 */\n");
      out.write("	  }\n");
      out.write("	</style>\n");
      out.write("    \n");
      out.write("\n");
      out.write("    ");
 
      List<Shain> shainList = (List<Shain>) request.getAttribute("shainList");

      if (shainList == null || shainList.isEmpty()) {
    
      out.write("\n");
      out.write("        <p>登録された社員はいません。</p>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr>\n");
      out.write("            <th>社員ID</th>\n");
      out.write("            <th>氏名</th>\n");
      out.write("            <th>性別</th>\n");
      out.write("            <th>備考</th>\n");
      out.write("      		<th>操作</th>\n");
      out.write("          </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("        ");
 for (Shain s : shainList) { 
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td>");
      out.print( s.getId() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( s.getName() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( "M".equals(s.getGender()) ? "男性" : "女性" );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( s.getNote() != null ? s.getNote() : "" );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("			  <a href=\"shain_hensyuu?id=");
      out.print( s.getId() );
      out.write("\">更新</a> |\n");
      out.write("			  <form action=\"shain_sakujyo\" method=\"post\" style=\"display:inline;\">\n");
      out.write("			    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( s.getId() );
      out.write("\">\n");
      out.write("			    <button type=\"submit\" onclick=\"return confirm('本当に削除しますか？');\" style=\"background:none; border:none; color:#4caf50; font-weight:bold; cursor:pointer;\">\n");
      out.write("			      削除\n");
      out.write("			    </button>\n");
      out.write("			  </form>\n");
      out.write("			</td>\n");
      out.write("          </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <a href=\"shain_touroku\" class=\"btn-back\">社員登録へ戻る</a>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
